feature: add scenario tests

diff --git a/deno-tlca/tasks/dev b/deno-tlca/tasks/dev
--- a/deno-tlca/tasks/dev
+++ b/deno-tlca/tasks/dev
@@ -21,6 +21,25 @@ build_parser() {
     )
 }
 
+scenario_tests() {
+    echo "---| scenario tests"
+
+    for FILE in "$PROJECT_HOME"/../tlca/scenarios/*.inp; do
+        echo "- scenario test: $FILE"
+        deno run --allow-read --unsafely-ignore-certificate-errors \
+            Repl.ts "$FILE" > t.txt || exit 1
+
+        if ! diff -q "$PROJECT_HOME"/../tlca/scenarios/$(basename "$FILE" .inp).out t.txt; then
+            echo "scenario test failed: $FILE"
+            diff "$PROJECT_HOME"/../tlca/scenarios/$(basename "$FILE" .inp).out t.txt
+            rm t.txt
+            exit 1
+        fi
+
+        rm t.txt
+    done
+}
+
 unit_tests() {
     echo "---| unit tests"
     cd "$PROJECT_HOME" || exit 1
@@ -38,6 +57,8 @@ case "$1" in
     echo "    Builds the parser from specs"
     echo "  run"
     echo "    Run all tasks"
+    echo "  scenario"
+    echo "    Run all scenario tests"
     echo "  unit"
     echo "    Run all unit tests"
     ;;
@@ -45,10 +66,15 @@ case "$1" in
 run)
     build_parser
     unit_tests
+    scenario_tests
     ;;
 
 parser)
     build_parser
+    ;;
+
+scenario)
+    scenario_tests
     ;;
 
 unit)
diff --git a/kotlin-tlca/tasks/dev b/kotlin-tlca/tasks/dev
--- a/kotlin-tlca/tasks/dev
+++ b/kotlin-tlca/tasks/dev
@@ -2,6 +2,12 @@
 
 PROJECT_HOME=$(dirname "$0")/..
 
+build_jar() {
+    echo "---| build JAR"
+    cd "$PROJECT_HOME" || exit 1
+    ./gradlew jar || exit 1
+}
+
 build_parser() {
     (
         echo "---| build parser"
@@ -18,6 +24,24 @@ build_parser() {
     )
 }
 
+scenario_tests() {
+    echo "---| scenario tests"
+
+    for FILE in "$PROJECT_HOME"/../tlca/scenarios/*.inp; do
+        echo "- scenario test: $FILE"
+        java -jar app/build/libs/app.jar "$FILE" > t.txt || exit 1
+
+        if ! diff -q "$PROJECT_HOME"/../tlca/scenarios/$(basename "$FILE" .inp).out t.txt; then
+            echo "scenario test failed: $FILE"
+            diff "$PROJECT_HOME"/../tlca/scenarios/$(basename "$FILE" .inp).out t.txt
+            rm t.txt
+            exit 1
+        fi
+
+        rm t.txt
+    done
+}
+
 unit_tests() {
     echo "---| unit tests"
     cd "$PROJECT_HOME" || exit 1
@@ -30,10 +54,14 @@ case "$1" in
     echo "Commands:"
     echo "  help"
     echo "    This help page"
+    echo "  jar"
+    echo "    Create the application's JAR file"
     echo "  parser"
     echo "    Builds the parser from specs"
     echo "  run"
     echo "    Run all tasks"
+    echo "  scenario"
+    echo "    Run all scenario tests"
     echo "  unit"
     echo "    Run all unit tests"
     ;;
@@ -41,10 +69,20 @@ case "$1" in
 run)
     build_parser
     unit_tests
+    build_jar
+    scenario_tests
+    ;;
+
+jar)
+    build_jar
     ;;
 
 parser)
     build_parser
+    ;;
+
+scenario)
+    scenario_tests
     ;;
 
 unit)
