kotlin-stlc: feature: compile to bytecode

diff --git a/kotlin-stlc/tasks/dev b/kotlin-stlc/tasks/dev
--- a/kotlin-stlc/tasks/dev
+++ b/kotlin-stlc/tasks/dev
@@ -2,6 +2,12 @@
 
 PROJECT_HOME=$(dirname "$0")/..
 
+build_jar() {
+    echo "---| build JAR"
+    cd "$PROJECT_HOME" || exit 1
+    ./gradlew jar || exit 1
+}
+
 build_parser() {
     (
         echo "---| build parser"
@@ -18,6 +24,45 @@ build_parser() {
     )
 }
 
+compiler_scenarios() {
+    echo "---| compiler scenario tests"
+
+    for FILE in "$PROJECT_HOME"/../stlc/scenarios/*.inp; do
+        echo "- scenario test: $FILE"
+        java -jar app/build/libs/app.jar "$FILE" $(basename "$FILE" .inp).bin || exit 1
+        deno run --allow-read ../stlc-bci/deno/bci.ts run $(basename "$FILE" .inp).bin > t.txt || exit 1
+
+        if ! diff -q "$PROJECT_HOME"/../stlc/scenarios/$(basename "$FILE" .inp).out t.txt; then
+            echo "scenario test failed: $FILE"
+            diff "$PROJECT_HOME"/../stlc/scenarios/$(basename "$FILE" .inp).out t.txt
+            rm t.txt
+            exit 1
+        fi
+
+        rm t.txt
+    done
+
+}
+
+interpreter_scenarios() {
+    echo "---| interpreter scenario tests"
+
+    for FILE in "$PROJECT_HOME"/../stlc/scenarios/*.inp; do
+        echo "- scenario test: $FILE"
+        java -jar app/build/libs/app.jar "$FILE" > t.txt || exit 1
+
+        if ! diff -q "$PROJECT_HOME"/../stlc/scenarios/$(basename "$FILE" .inp).out t.txt; then
+            echo "scenario test failed: $FILE"
+            diff "$PROJECT_HOME"/../stlc/scenarios/$(basename "$FILE" .inp).out t.txt
+            rm t.txt
+            exit 1
+        fi
+
+        rm t.txt
+    done
+
+}
+
 unit_tests() {
     echo "---| unit tests"
     cd "$PROJECT_HOME" || exit 1
@@ -30,6 +75,12 @@ case "$1" in
     echo "Commands:"
     echo "  help"
     echo "    This help page"
+    echo "  compiler_scenarios"
+    echo "    Run the scenarios using the compiled bytecode"
+    echo "  interpreter_scenarios"
+    echo "    Run the scenarios using the interpreter"
+    echo "  jar"
+    echo "    Create the application's JAR file"
     echo "  parser"
     echo "    Builds the parser from specs"
     echo "  run"
@@ -38,9 +89,20 @@ case "$1" in
     echo "    Run all unit tests"
     ;;
 
+compiler_scenarios)
+    compiler_scenarios
+    ;;
+
+interpreter_scenarios)
+    interpreter_scenarios
+    ;;
+
 run)
     build_parser
     unit_tests
+    build_jar
+    interpreter_scenarios
+    compiler_scenarios
     ;;
 
 parser)
